# Generated by Django 4.0.4 on 2022-05-18 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_student_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hname', models.CharField(max_length=100)),
                ('doctor', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('bp', models.CharField(max_length=100)),
                ('sl', models.CharField(max_length=100)),
                ('dw', models.CharField(max_length=100)),
                ('li', models.CharField(max_length=100)),
                ('admitdate', models.CharField(max_length=100)),
                ('dischargedate', models.CharField(max_length=100)),
            ],
        ),
    ]
