# Generated by Django 4.0.4 on 2022-05-18 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_patient_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='username',
        ),
    ]
