# Generated by Django 4.0.4 on 2022-05-29 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_patient_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pame', models.CharField(max_length=100)),
                ('hname', models.CharField(max_length=100)),
                ('doctor', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('time', models.TimeField()),
            ],
        ),
    ]
